language: node_js
node_js:
  - "6"

sudo: false

cache:
  directories:
    - node_modules

install:
  - npm install -g gulp mocha
  - npm install

script:
  - npm run test-ci

after_script:
  - "cat ./test-coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
